CREATE TABLE Gym_Member(
	UName VARCHAR(50) PRIMARY KEY NOT NULL,
	pWord VARCHAR(50) NOT NULL,
	fName VARCHAR(50) NOT NULL,
	lName VARCHAR(50) NOT NULL, 
	DOB DATE, 
	wieght INT, 
	reg_date DATE NOT NULL, 
	goal VARCHAR(50), 
	gender VARCHAR(50), 
	subscription VARCHAR(50) NOT NULL, 
	trnUName VARCHAR(50) REFERENCES Trainer.Uname 
	);

CREATE TABLE Alergy(
	UName VARCHAR(50) PRIMARY KEY REFERENCES Gym_Member.UName,
	alergy VARCHAR(50)
	);

CREATE TABLE Trainer(
	UName VARCHAR(50) PRIMARY KEY NOT NULL,
	pWord VARCHAR(50) NOT NULL,
	fName VARCHAR(50) NOT NULL,
	lName VARCHAR(50) NOT NULL, 
	gender VARCHAR(50),
	DOB DATE, wieght INT, 
	exp_lvl INT DEFAULT 0,
	rating FLOAT(2),
	startDate DATE
	);

CREATE TABLE TRN_PAST_GYM(
	UName VARCHAR(50) PRIMARY KEY REFERENCES Trainer.UName,
	gymName VARCHAR(50),
	);

CREATE TABLE Training_Session(
	sessionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	start_time TIME NOT NULL,
	end_time TIME NOT NULL,
	TrainerUName VARCHAR(50) REFERENCES Trainer.UName,
	MemberUName VARCHAR(50) REFERENCES Member.UName
	);
CREATE TABLE GYM_OWNER(
	UName VARCHAR(50) PRIMARY KEY NOT NULL,
	pWord VARCHAR(50) NOT NULL,
	fName VARCHAR(50) NOT NULL,
	lName VARCHAR(50) NOT NULL,
	DOB DATE
	);
CREATE TABLE Gym_Admin(
	UName VARCHAR(50) PRIMARY KEY NOT NULL,
	pWord VARCHAR(50) NOT NULL,
	fName VARCHAR(50) NOT NULL,
	lName VARCHAR(50) NOT NULL,
	DOB DATE
	);
CREATE TABLE Franchise_Application(
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	location VARCHAR(50) NOT NULL,
	demand INT NOT NULL,
	proposition VARCHAR(50) NOT NULL,
	adminUName VARCHAR(50) REFERENCES Gym_Admin.UName,
	ownerUName VARCHAR(50) REFERENCES GYM_OWNER.UName
	);

CREATE TABLE Gym(
	id int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	rating FLOAT(2) DEFAULT 0,
	location VARCHAR(50) NOT NULL,
	ownerUName VARCHAR(50) REFERENCES GYM_OWNER.UName,
	noMembers INT DEFAULT 0,
	noTrainers INT DEFAULT 0,
	finances INT DEFAULT 0
	);
CREATE TABLE Trainer_Feedback(
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	rating FLOAT(2) NOT NULL,
	comment VARCHAR(50) NOT NULL,
	trainerUName VARCHAR(50) REFERENCES Trainer.UName,
	memberUName VARCHAR(50) REFERENCES Gym_Member.UName
	);
CREATE TABLE Workout_Plan(
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	name VARCHAR(50) NOT NULL,
	type VARCHAR(50) NOT NULL,
	trainerUName VARCHAR(50) REFERENCES Trainer.UName,
	memUName VARCHAR(50) REFERENCES Gym_Member.UName
	);
CREATE TABLE workout_day(
	planID INT PRIMARY KEY REFERENCES Workout_Plan.id,
	wDay VARCHAR(50) NOT NULL
	);

CREATE TABLE exercise(
	name VARCHAR(50) PRIMARY KEY NOT NULL,
	machine VARCHAR(50) NOT NULL,
	targetMuscle VARCHAR(50) NOT NULL
	);

CREATE TABLE ExerciseInDay(
	exerciseName VARCHAR(50) REFERENCES exercise.name,
	dayFK VARCHAR(50)REFERENCES workout_day.wDay,
	planFK INT REFERENCES Workout_Plan.id
	CONSTRAINT compositeKey PRIMARY KEY(dayFK,planFK)
	);
CREATE TABLE Meal(
	name VARCHAR(50) PRIMARY KEY NOT NULL,
	portionSize INT NOT NULL,
	protein INT NOT NULL,
	carbs INT NOT NULL,
	fat INT NOT NULL,
	fiber INT NOT NULL
	);
CREATE TABLE Diet_Plan(
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	name VARCHAR(50) NOT NULL,
	type VARCHAR(50) NOT NULL,
	purpose VARCHAR(50) NOT NULL,
	trainerUName VARCHAR(50) REFERENCES Trainer.UName,
	memUName VARCHAR(50) REFERENCES Gym_Member.UName
	);
CREATE TABLE meal_day(
	planID INT PRIMARY KEY REFERENCES Diet_Plan.id,
	mDay VARCHAR(50) NOT NULL
	);
CREATE TABLE MealInDay(
	mealName VARCHAR(50) REFERENCES Meal.name,
	dayFK VARCHAR(50) REFERENCES meal_day.mDay,
	planFK INT REFERENCES Diet_Plan.id
	CONSTRAINT compositeKey PRIMARY KEY (dayFK,planFK) 
	);
CREATE TABLE GYM_Attendance(
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	memberUName VARCHAR(50) REFERENCES Gym_Member.UName,
	trainerUName VARCHAR(50) REFERENCES Trainer.UName,
	attendance PERCENTAGE NOT NULL,
	);
