
namespace DBPROJ_VF
{
    partial class Login
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Login));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.registration = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.regDrop = new Bunifu.UI.WinForms.BunifuDropdown();
            this.Password = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Username = new Bunifu.UI.WinForms.BunifuTextBox();
            this.login_label = new System.Windows.Forms.Label();
            this.label_pass = new Bunifu.UI.WinForms.BunifuLabel();
            this.Label_uname = new Bunifu.UI.WinForms.BunifuLabel();
            this.trainer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.member = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.owner = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Admin = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGradientPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuGradientPanel1.Controls.Add(this.registration);
            this.bunifuGradientPanel1.Controls.Add(this.regDrop);
            this.bunifuGradientPanel1.Controls.Add(this.Password);
            this.bunifuGradientPanel1.Controls.Add(this.Username);
            this.bunifuGradientPanel1.Controls.Add(this.login_label);
            this.bunifuGradientPanel1.Controls.Add(this.label_pass);
            this.bunifuGradientPanel1.Controls.Add(this.Label_uname);
            this.bunifuGradientPanel1.Controls.Add(this.trainer);
            this.bunifuGradientPanel1.Controls.Add(this.member);
            this.bunifuGradientPanel1.Controls.Add(this.owner);
            this.bunifuGradientPanel1.Controls.Add(this.Admin);
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.White;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.DeepSkyBlue;
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.Teal;
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, -3);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(804, 466);
            this.bunifuGradientPanel1.TabIndex = 0;
            this.bunifuGradientPanel1.Click += new System.EventHandler(this.bunifuGradientPanel1_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(253, 328);
            this.bunifuLabel1.MaximumSize = new System.Drawing.Size(500, 30);
            this.bunifuLabel1.MinimumSize = new System.Drawing.Size(500, 30);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(500, 30);
            this.bunifuLabel1.TabIndex = 11;
            this.bunifuLabel1.Text = "Not A Member? Select Dropdown and register!";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // registration
            // 
            this.registration.AllowAnimations = true;
            this.registration.AllowMouseEffects = true;
            this.registration.AllowToggling = false;
            this.registration.AnimationSpeed = 200;
            this.registration.AutoGenerateColors = false;
            this.registration.AutoRoundBorders = false;
            this.registration.AutoSizeLeftIcon = true;
            this.registration.AutoSizeRightIcon = true;
            this.registration.BackColor = System.Drawing.Color.Transparent;
            this.registration.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.registration.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("registration.BackgroundImage")));
            this.registration.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registration.ButtonText = "Register";
            this.registration.ButtonTextMarginLeft = 0;
            this.registration.ColorContrastOnClick = 45;
            this.registration.ColorContrastOnHover = 45;
            this.registration.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.registration.CustomizableEdges = borderEdges1;
            this.registration.DialogResult = System.Windows.Forms.DialogResult.None;
            this.registration.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.registration.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.registration.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.registration.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.registration.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.registration.ForeColor = System.Drawing.Color.White;
            this.registration.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.registration.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.registration.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.registration.IconMarginLeft = 11;
            this.registration.IconPadding = 10;
            this.registration.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.registration.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.registration.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.registration.IconSize = 25;
            this.registration.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.registration.IdleBorderRadius = 1;
            this.registration.IdleBorderThickness = 1;
            this.registration.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.registration.IdleIconLeftImage = null;
            this.registration.IdleIconRightImage = null;
            this.registration.IndicateFocus = false;
            this.registration.Location = new System.Drawing.Point(331, 407);
            this.registration.Name = "registration";
            this.registration.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.registration.OnDisabledState.BorderRadius = 1;
            this.registration.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registration.OnDisabledState.BorderThickness = 1;
            this.registration.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.registration.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.registration.OnDisabledState.IconLeftImage = null;
            this.registration.OnDisabledState.IconRightImage = null;
            this.registration.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.registration.onHoverState.BorderRadius = 1;
            this.registration.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registration.onHoverState.BorderThickness = 1;
            this.registration.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.registration.onHoverState.ForeColor = System.Drawing.Color.White;
            this.registration.onHoverState.IconLeftImage = null;
            this.registration.onHoverState.IconRightImage = null;
            this.registration.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.registration.OnIdleState.BorderRadius = 1;
            this.registration.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registration.OnIdleState.BorderThickness = 1;
            this.registration.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.registration.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.registration.OnIdleState.IconLeftImage = null;
            this.registration.OnIdleState.IconRightImage = null;
            this.registration.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.registration.OnPressedState.BorderRadius = 1;
            this.registration.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registration.OnPressedState.BorderThickness = 1;
            this.registration.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.registration.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.registration.OnPressedState.IconLeftImage = null;
            this.registration.OnPressedState.IconRightImage = null;
            this.registration.Size = new System.Drawing.Size(150, 39);
            this.registration.TabIndex = 10;
            this.registration.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.registration.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.registration.TextMarginLeft = 0;
            this.registration.TextPadding = new System.Windows.Forms.Padding(0);
            this.registration.UseDefaultRadiusAndThickness = true;
            this.registration.Click += new System.EventHandler(this.registration_Click);
            // 
            // regDrop
            // 
            this.regDrop.BackColor = System.Drawing.Color.Transparent;
            this.regDrop.BackgroundColor = System.Drawing.Color.White;
            this.regDrop.BorderColor = System.Drawing.Color.Silver;
            this.regDrop.BorderRadius = 1;
            this.regDrop.Color = System.Drawing.Color.Silver;
            this.regDrop.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.regDrop.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.regDrop.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.regDrop.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.regDrop.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.regDrop.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.regDrop.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.regDrop.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.regDrop.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.regDrop.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.regDrop.FillDropDown = true;
            this.regDrop.FillIndicator = false;
            this.regDrop.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.regDrop.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.regDrop.ForeColor = System.Drawing.Color.Black;
            this.regDrop.FormattingEnabled = true;
            this.regDrop.Icon = null;
            this.regDrop.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.regDrop.IndicatorColor = System.Drawing.Color.Gray;
            this.regDrop.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.regDrop.ItemBackColor = System.Drawing.Color.White;
            this.regDrop.ItemBorderColor = System.Drawing.Color.White;
            this.regDrop.ItemForeColor = System.Drawing.Color.Black;
            this.regDrop.ItemHeight = 26;
            this.regDrop.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.regDrop.ItemHighLightForeColor = System.Drawing.Color.White;
            this.regDrop.Items.AddRange(new object[] {
            "Member",
            "Owner",
            "Trainer"});
            this.regDrop.ItemTopMargin = 3;
            this.regDrop.Location = new System.Drawing.Point(280, 354);
            this.regDrop.Name = "regDrop";
            this.regDrop.Size = new System.Drawing.Size(260, 32);
            this.regDrop.TabIndex = 9;
            this.regDrop.Text = null;
            this.regDrop.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.regDrop.TextLeftMargin = 5;
            this.regDrop.SelectedIndexChanged += new System.EventHandler(this.regDrop_SelectedIndexChanged);
            // 
            // Password
            // 
            this.Password.AcceptsReturn = false;
            this.Password.AcceptsTab = false;
            this.Password.AnimationSpeed = 200;
            this.Password.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Password.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Password.BackColor = System.Drawing.Color.Transparent;
            this.Password.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Password.BackgroundImage")));
            this.Password.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Password.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Password.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Password.BorderColorIdle = System.Drawing.Color.Silver;
            this.Password.BorderRadius = 1;
            this.Password.BorderThickness = 1;
            this.Password.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Password.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Password.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Password.DefaultText = "";
            this.Password.FillColor = System.Drawing.Color.White;
            this.Password.HideSelection = true;
            this.Password.IconLeft = null;
            this.Password.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Password.IconPadding = 10;
            this.Password.IconRight = null;
            this.Password.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Password.Lines = new string[0];
            this.Password.Location = new System.Drawing.Point(480, 204);
            this.Password.MaxLength = 32767;
            this.Password.MinimumSize = new System.Drawing.Size(1, 1);
            this.Password.Modified = false;
            this.Password.Multiline = false;
            this.Password.Name = "Password";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Password.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Password.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Password.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Password.OnIdleState = stateProperties4;
            this.Password.Padding = new System.Windows.Forms.Padding(3);
            this.Password.PasswordChar = '\0';
            this.Password.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Password.PlaceholderText = "EX: PASSWORD";
            this.Password.ReadOnly = false;
            this.Password.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Password.SelectedText = "";
            this.Password.SelectionLength = 0;
            this.Password.SelectionStart = 0;
            this.Password.ShortcutsEnabled = true;
            this.Password.Size = new System.Drawing.Size(260, 41);
            this.Password.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Password.TabIndex = 5;
            this.Password.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Password.TextMarginBottom = 0;
            this.Password.TextMarginLeft = 3;
            this.Password.TextMarginTop = 0;
            this.Password.TextPlaceholder = "EX: PASSWORD";
            this.Password.UseSystemPasswordChar = false;
            this.Password.WordWrap = true;
            this.Password.TextChanged += new System.EventHandler(this.Password_TextChanged);
            // 
            // Username
            // 
            this.Username.AcceptsReturn = false;
            this.Username.AcceptsTab = false;
            this.Username.AnimationSpeed = 200;
            this.Username.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Username.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Username.BackColor = System.Drawing.Color.Transparent;
            this.Username.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Username.BackgroundImage")));
            this.Username.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Username.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Username.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Username.BorderColorIdle = System.Drawing.Color.Silver;
            this.Username.BorderRadius = 1;
            this.Username.BorderThickness = 1;
            this.Username.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Username.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Username.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Username.DefaultText = "";
            this.Username.FillColor = System.Drawing.Color.White;
            this.Username.HideSelection = true;
            this.Username.IconLeft = null;
            this.Username.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Username.IconPadding = 10;
            this.Username.IconRight = null;
            this.Username.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Username.Lines = new string[0];
            this.Username.Location = new System.Drawing.Point(480, 98);
            this.Username.MaxLength = 32767;
            this.Username.MinimumSize = new System.Drawing.Size(1, 1);
            this.Username.Modified = false;
            this.Username.Multiline = false;
            this.Username.Name = "Username";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Username.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Username.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Username.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Username.OnIdleState = stateProperties8;
            this.Username.Padding = new System.Windows.Forms.Padding(3);
            this.Username.PasswordChar = '\0';
            this.Username.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Username.PlaceholderText = "EX: USER123";
            this.Username.ReadOnly = false;
            this.Username.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Username.SelectedText = "";
            this.Username.SelectionLength = 0;
            this.Username.SelectionStart = 0;
            this.Username.ShortcutsEnabled = true;
            this.Username.Size = new System.Drawing.Size(260, 41);
            this.Username.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Username.TabIndex = 4;
            this.Username.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Username.TextMarginBottom = 0;
            this.Username.TextMarginLeft = 3;
            this.Username.TextMarginTop = 0;
            this.Username.TextPlaceholder = "EX: USER123";
            this.Username.UseSystemPasswordChar = false;
            this.Username.WordWrap = true;
            // 
            // login_label
            // 
            this.login_label.AutoSize = true;
            this.login_label.Font = new System.Drawing.Font("Microsoft Sans Serif", 48F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.login_label.Location = new System.Drawing.Point(34, 57);
            this.login_label.MaximumSize = new System.Drawing.Size(10000, 1000);
            this.login_label.MinimumSize = new System.Drawing.Size(200, 200);
            this.login_label.Name = "login_label";
            this.login_label.Size = new System.Drawing.Size(232, 200);
            this.login_label.TabIndex = 8;
            this.login_label.Text = "Login";
            // 
            // label_pass
            // 
            this.label_pass.AllowParentOverrides = false;
            this.label_pass.AutoEllipsis = false;
            this.label_pass.Cursor = System.Windows.Forms.Cursors.Default;
            this.label_pass.CursorType = System.Windows.Forms.Cursors.Default;
            this.label_pass.Font = new System.Drawing.Font("Sans Serif Collection", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label_pass.Location = new System.Drawing.Point(367, 204);
            this.label_pass.MinimumSize = new System.Drawing.Size(150, 50);
            this.label_pass.Name = "label_pass";
            this.label_pass.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.label_pass.Size = new System.Drawing.Size(150, 50);
            this.label_pass.TabIndex = 7;
            this.label_pass.Text = "Password";
            this.label_pass.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.label_pass.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Label_uname
            // 
            this.Label_uname.AllowParentOverrides = false;
            this.Label_uname.AutoEllipsis = false;
            this.Label_uname.Cursor = System.Windows.Forms.Cursors.Default;
            this.Label_uname.CursorType = System.Windows.Forms.Cursors.Default;
            this.Label_uname.Font = new System.Drawing.Font("Sans Serif Collection", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Label_uname.Location = new System.Drawing.Point(367, 98);
            this.Label_uname.MinimumSize = new System.Drawing.Size(150, 50);
            this.Label_uname.Name = "Label_uname";
            this.Label_uname.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.Label_uname.Size = new System.Drawing.Size(150, 50);
            this.Label_uname.TabIndex = 6;
            this.Label_uname.Text = "Username";
            this.Label_uname.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.Label_uname.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.Label_uname.Click += new System.EventHandler(this.Label_uname_Click);
            // 
            // trainer
            // 
            this.trainer.AllowAnimations = true;
            this.trainer.AllowMouseEffects = true;
            this.trainer.AllowToggling = true;
            this.trainer.AnimationSpeed = 200;
            this.trainer.AutoGenerateColors = false;
            this.trainer.AutoRoundBorders = true;
            this.trainer.AutoSizeLeftIcon = true;
            this.trainer.AutoSizeRightIcon = true;
            this.trainer.BackColor = System.Drawing.Color.Transparent;
            this.trainer.BackColor1 = System.Drawing.Color.Azure;
            this.trainer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("trainer.BackgroundImage")));
            this.trainer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.trainer.ButtonText = "Trainer";
            this.trainer.ButtonTextMarginLeft = 0;
            this.trainer.CausesValidation = false;
            this.trainer.ColorContrastOnClick = 45;
            this.trainer.ColorContrastOnHover = 60;
            this.trainer.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.trainer.CustomizableEdges = borderEdges2;
            this.trainer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.trainer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.trainer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.trainer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.trainer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.trainer.Font = new System.Drawing.Font("Sans Serif Collection", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.trainer.ForeColor = System.Drawing.Color.Black;
            this.trainer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.trainer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.trainer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.trainer.IconMarginLeft = 11;
            this.trainer.IconPadding = 10;
            this.trainer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.trainer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.trainer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.trainer.IconSize = 25;
            this.trainer.IdleBorderColor = System.Drawing.Color.Azure;
            this.trainer.IdleBorderRadius = 37;
            this.trainer.IdleBorderThickness = 1;
            this.trainer.IdleFillColor = System.Drawing.Color.Azure;
            this.trainer.IdleIconLeftImage = null;
            this.trainer.IdleIconRightImage = null;
            this.trainer.IndicateFocus = true;
            this.trainer.Location = new System.Drawing.Point(418, 270);
            this.trainer.Name = "trainer";
            this.trainer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.trainer.OnDisabledState.BorderRadius = 1;
            this.trainer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.trainer.OnDisabledState.BorderThickness = 1;
            this.trainer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.trainer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.trainer.OnDisabledState.IconLeftImage = null;
            this.trainer.OnDisabledState.IconRightImage = null;
            this.trainer.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.trainer.onHoverState.BorderRadius = 1;
            this.trainer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.trainer.onHoverState.BorderThickness = 1;
            this.trainer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.trainer.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.trainer.onHoverState.IconLeftImage = null;
            this.trainer.onHoverState.IconRightImage = null;
            this.trainer.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.trainer.OnIdleState.BorderRadius = 1;
            this.trainer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.trainer.OnIdleState.BorderThickness = 1;
            this.trainer.OnIdleState.FillColor = System.Drawing.Color.Azure;
            this.trainer.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.trainer.OnIdleState.IconLeftImage = null;
            this.trainer.OnIdleState.IconRightImage = null;
            this.trainer.OnPressedState.BorderColor = System.Drawing.Color.Azure;
            this.trainer.OnPressedState.BorderRadius = 1;
            this.trainer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.trainer.OnPressedState.BorderThickness = 1;
            this.trainer.OnPressedState.FillColor = System.Drawing.Color.Azure;
            this.trainer.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.trainer.OnPressedState.IconLeftImage = null;
            this.trainer.OnPressedState.IconRightImage = null;
            this.trainer.Size = new System.Drawing.Size(150, 39);
            this.trainer.TabIndex = 3;
            this.trainer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.trainer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.trainer.TextMarginLeft = 0;
            this.trainer.TextPadding = new System.Windows.Forms.Padding(0);
            this.trainer.UseDefaultRadiusAndThickness = true;
            this.trainer.Click += new System.EventHandler(this.trainer_Click);
            // 
            // member
            // 
            this.member.AllowAnimations = true;
            this.member.AllowMouseEffects = true;
            this.member.AllowToggling = true;
            this.member.AnimationSpeed = 200;
            this.member.AutoGenerateColors = false;
            this.member.AutoRoundBorders = true;
            this.member.AutoSizeLeftIcon = true;
            this.member.AutoSizeRightIcon = true;
            this.member.BackColor = System.Drawing.Color.Transparent;
            this.member.BackColor1 = System.Drawing.Color.Azure;
            this.member.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("member.BackgroundImage")));
            this.member.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.member.ButtonText = "Member";
            this.member.ButtonTextMarginLeft = 0;
            this.member.CausesValidation = false;
            this.member.ColorContrastOnClick = 45;
            this.member.ColorContrastOnHover = 60;
            this.member.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.member.CustomizableEdges = borderEdges3;
            this.member.DialogResult = System.Windows.Forms.DialogResult.None;
            this.member.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.member.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.member.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.member.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.member.Font = new System.Drawing.Font("Sans Serif Collection", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.member.ForeColor = System.Drawing.Color.Black;
            this.member.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.member.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.member.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.member.IconMarginLeft = 11;
            this.member.IconPadding = 10;
            this.member.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.member.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.member.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.member.IconSize = 25;
            this.member.IdleBorderColor = System.Drawing.Color.Azure;
            this.member.IdleBorderRadius = 37;
            this.member.IdleBorderThickness = 1;
            this.member.IdleFillColor = System.Drawing.Color.Azure;
            this.member.IdleIconLeftImage = null;
            this.member.IdleIconRightImage = null;
            this.member.IndicateFocus = true;
            this.member.Location = new System.Drawing.Point(238, 270);
            this.member.Name = "member";
            this.member.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.member.OnDisabledState.BorderRadius = 1;
            this.member.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.member.OnDisabledState.BorderThickness = 1;
            this.member.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.member.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.member.OnDisabledState.IconLeftImage = null;
            this.member.OnDisabledState.IconRightImage = null;
            this.member.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.member.onHoverState.BorderRadius = 1;
            this.member.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.member.onHoverState.BorderThickness = 1;
            this.member.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.member.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.member.onHoverState.IconLeftImage = null;
            this.member.onHoverState.IconRightImage = null;
            this.member.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.member.OnIdleState.BorderRadius = 1;
            this.member.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.member.OnIdleState.BorderThickness = 1;
            this.member.OnIdleState.FillColor = System.Drawing.Color.Azure;
            this.member.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.member.OnIdleState.IconLeftImage = null;
            this.member.OnIdleState.IconRightImage = null;
            this.member.OnPressedState.BorderColor = System.Drawing.Color.Azure;
            this.member.OnPressedState.BorderRadius = 1;
            this.member.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.member.OnPressedState.BorderThickness = 1;
            this.member.OnPressedState.FillColor = System.Drawing.Color.Azure;
            this.member.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.member.OnPressedState.IconLeftImage = null;
            this.member.OnPressedState.IconRightImage = null;
            this.member.Size = new System.Drawing.Size(150, 39);
            this.member.TabIndex = 2;
            this.member.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.member.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.member.TextMarginLeft = 0;
            this.member.TextPadding = new System.Windows.Forms.Padding(0);
            this.member.UseDefaultRadiusAndThickness = true;
            this.member.Click += new System.EventHandler(this.member_Click);
            // 
            // owner
            // 
            this.owner.AllowAnimations = true;
            this.owner.AllowMouseEffects = true;
            this.owner.AllowToggling = true;
            this.owner.AnimationSpeed = 200;
            this.owner.AutoGenerateColors = false;
            this.owner.AutoRoundBorders = true;
            this.owner.AutoSizeLeftIcon = true;
            this.owner.AutoSizeRightIcon = true;
            this.owner.BackColor = System.Drawing.Color.Transparent;
            this.owner.BackColor1 = System.Drawing.Color.Azure;
            this.owner.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("owner.BackgroundImage")));
            this.owner.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.owner.ButtonText = "Owner";
            this.owner.ButtonTextMarginLeft = 0;
            this.owner.CausesValidation = false;
            this.owner.ColorContrastOnClick = 45;
            this.owner.ColorContrastOnHover = 60;
            this.owner.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.owner.CustomizableEdges = borderEdges4;
            this.owner.DialogResult = System.Windows.Forms.DialogResult.None;
            this.owner.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.owner.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.owner.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.owner.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.owner.Font = new System.Drawing.Font("Sans Serif Collection", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.owner.ForeColor = System.Drawing.Color.Black;
            this.owner.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.owner.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.owner.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.owner.IconMarginLeft = 11;
            this.owner.IconPadding = 10;
            this.owner.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.owner.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.owner.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.owner.IconSize = 25;
            this.owner.IdleBorderColor = System.Drawing.Color.Azure;
            this.owner.IdleBorderRadius = 37;
            this.owner.IdleBorderThickness = 1;
            this.owner.IdleFillColor = System.Drawing.Color.Azure;
            this.owner.IdleIconLeftImage = null;
            this.owner.IdleIconRightImage = null;
            this.owner.IndicateFocus = true;
            this.owner.Location = new System.Drawing.Point(607, 270);
            this.owner.Name = "owner";
            this.owner.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.owner.OnDisabledState.BorderRadius = 1;
            this.owner.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.owner.OnDisabledState.BorderThickness = 1;
            this.owner.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.owner.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.owner.OnDisabledState.IconLeftImage = null;
            this.owner.OnDisabledState.IconRightImage = null;
            this.owner.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.owner.onHoverState.BorderRadius = 1;
            this.owner.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.owner.onHoverState.BorderThickness = 1;
            this.owner.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.owner.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.owner.onHoverState.IconLeftImage = null;
            this.owner.onHoverState.IconRightImage = null;
            this.owner.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.owner.OnIdleState.BorderRadius = 1;
            this.owner.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.owner.OnIdleState.BorderThickness = 1;
            this.owner.OnIdleState.FillColor = System.Drawing.Color.Azure;
            this.owner.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.owner.OnIdleState.IconLeftImage = null;
            this.owner.OnIdleState.IconRightImage = null;
            this.owner.OnPressedState.BorderColor = System.Drawing.Color.Azure;
            this.owner.OnPressedState.BorderRadius = 1;
            this.owner.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.owner.OnPressedState.BorderThickness = 1;
            this.owner.OnPressedState.FillColor = System.Drawing.Color.Azure;
            this.owner.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.owner.OnPressedState.IconLeftImage = null;
            this.owner.OnPressedState.IconRightImage = null;
            this.owner.Size = new System.Drawing.Size(150, 39);
            this.owner.TabIndex = 1;
            this.owner.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.owner.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.owner.TextMarginLeft = 0;
            this.owner.TextPadding = new System.Windows.Forms.Padding(0);
            this.owner.UseDefaultRadiusAndThickness = true;
            this.owner.Click += new System.EventHandler(this.owner_Click);
            // 
            // Admin
            // 
            this.Admin.AllowAnimations = true;
            this.Admin.AllowMouseEffects = true;
            this.Admin.AllowToggling = true;
            this.Admin.AnimationSpeed = 200;
            this.Admin.AutoGenerateColors = false;
            this.Admin.AutoRoundBorders = true;
            this.Admin.AutoSizeLeftIcon = true;
            this.Admin.AutoSizeRightIcon = true;
            this.Admin.BackColor = System.Drawing.Color.Transparent;
            this.Admin.BackColor1 = System.Drawing.Color.Azure;
            this.Admin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Admin.BackgroundImage")));
            this.Admin.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Admin.ButtonText = "Admin";
            this.Admin.ButtonTextMarginLeft = 0;
            this.Admin.CausesValidation = false;
            this.Admin.ColorContrastOnClick = 45;
            this.Admin.ColorContrastOnHover = 60;
            this.Admin.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.Admin.CustomizableEdges = borderEdges5;
            this.Admin.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Admin.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Admin.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Admin.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Admin.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Admin.Font = new System.Drawing.Font("Sans Serif Collection", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Admin.ForeColor = System.Drawing.Color.Black;
            this.Admin.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Admin.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Admin.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Admin.IconMarginLeft = 11;
            this.Admin.IconPadding = 10;
            this.Admin.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Admin.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Admin.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Admin.IconSize = 25;
            this.Admin.IdleBorderColor = System.Drawing.Color.Azure;
            this.Admin.IdleBorderRadius = 37;
            this.Admin.IdleBorderThickness = 1;
            this.Admin.IdleFillColor = System.Drawing.Color.Azure;
            this.Admin.IdleIconLeftImage = null;
            this.Admin.IdleIconRightImage = null;
            this.Admin.IndicateFocus = true;
            this.Admin.Location = new System.Drawing.Point(50, 270);
            this.Admin.Name = "Admin";
            this.Admin.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Admin.OnDisabledState.BorderRadius = 1;
            this.Admin.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Admin.OnDisabledState.BorderThickness = 1;
            this.Admin.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Admin.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Admin.OnDisabledState.IconLeftImage = null;
            this.Admin.OnDisabledState.IconRightImage = null;
            this.Admin.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.Admin.onHoverState.BorderRadius = 1;
            this.Admin.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Admin.onHoverState.BorderThickness = 1;
            this.Admin.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.Admin.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.Admin.onHoverState.IconLeftImage = null;
            this.Admin.onHoverState.IconRightImage = null;
            this.Admin.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.Admin.OnIdleState.BorderRadius = 1;
            this.Admin.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Admin.OnIdleState.BorderThickness = 1;
            this.Admin.OnIdleState.FillColor = System.Drawing.Color.Azure;
            this.Admin.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Admin.OnIdleState.IconLeftImage = null;
            this.Admin.OnIdleState.IconRightImage = null;
            this.Admin.OnPressedState.BorderColor = System.Drawing.Color.Azure;
            this.Admin.OnPressedState.BorderRadius = 1;
            this.Admin.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Admin.OnPressedState.BorderThickness = 1;
            this.Admin.OnPressedState.FillColor = System.Drawing.Color.Azure;
            this.Admin.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.Admin.OnPressedState.IconLeftImage = null;
            this.Admin.OnPressedState.IconRightImage = null;
            this.Admin.Size = new System.Drawing.Size(150, 39);
            this.Admin.TabIndex = 0;
            this.Admin.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Admin.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Admin.TextMarginLeft = 0;
            this.Admin.TextPadding = new System.Windows.Forms.Padding(0);
            this.Admin.UseDefaultRadiusAndThickness = true;
            this.Admin.Click += new System.EventHandler(this.Admin_Click);
            // 
            // Login
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Fixed3D;
            this.Name = "Login";
            this.Text = "Form1";
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Admin;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton trainer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton member;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton owner;
        private System.Windows.Forms.Label login_label;
        private Bunifu.UI.WinForms.BunifuLabel label_pass;
        private Bunifu.UI.WinForms.BunifuLabel Label_uname;
        private Bunifu.UI.WinForms.BunifuTextBox Password;
        private Bunifu.UI.WinForms.BunifuTextBox Username;
        private Bunifu.UI.WinForms.BunifuDropdown regDrop;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton registration;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
    }
}

