namespace DBPROJ_VF
{
    partial class MemberMenu
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MemberMenu));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.CreateWorkout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ChooseWorkout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.DeitPlanning = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ChooseDiet = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SessionBook = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Rate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label1 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // CreateWorkout
            // 
            this.CreateWorkout.AllowAnimations = true;
            this.CreateWorkout.AllowMouseEffects = true;
            this.CreateWorkout.AllowToggling = false;
            this.CreateWorkout.AnimationSpeed = 200;
            this.CreateWorkout.AutoGenerateColors = false;
            this.CreateWorkout.AutoRoundBorders = false;
            this.CreateWorkout.AutoSizeLeftIcon = true;
            this.CreateWorkout.AutoSizeRightIcon = true;
            this.CreateWorkout.BackColor = System.Drawing.Color.Transparent;
            this.CreateWorkout.BackColor1 = System.Drawing.Color.LightCyan;
            this.CreateWorkout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CreateWorkout.BackgroundImage")));
            this.CreateWorkout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateWorkout.ButtonText = "Create Workout";
            this.CreateWorkout.ButtonTextMarginLeft = 0;
            this.CreateWorkout.ColorContrastOnClick = 45;
            this.CreateWorkout.ColorContrastOnHover = 45;
            this.CreateWorkout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.CreateWorkout.CustomizableEdges = borderEdges7;
            this.CreateWorkout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.CreateWorkout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CreateWorkout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CreateWorkout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CreateWorkout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.CreateWorkout.Font = new System.Drawing.Font("Segoe UI", 20F);
            this.CreateWorkout.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.CreateWorkout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.CreateWorkout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.CreateWorkout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.CreateWorkout.IconMarginLeft = 11;
            this.CreateWorkout.IconPadding = 10;
            this.CreateWorkout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.CreateWorkout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.CreateWorkout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.CreateWorkout.IconSize = 25;
            this.CreateWorkout.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.CreateWorkout.IdleBorderRadius = 100;
            this.CreateWorkout.IdleBorderThickness = 3;
            this.CreateWorkout.IdleFillColor = System.Drawing.Color.LightCyan;
            this.CreateWorkout.IdleIconLeftImage = null;
            this.CreateWorkout.IdleIconRightImage = null;
            this.CreateWorkout.IndicateFocus = false;
            this.CreateWorkout.Location = new System.Drawing.Point(67, 126);
            this.CreateWorkout.Name = "CreateWorkout";
            this.CreateWorkout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CreateWorkout.OnDisabledState.BorderRadius = 100;
            this.CreateWorkout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateWorkout.OnDisabledState.BorderThickness = 3;
            this.CreateWorkout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CreateWorkout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CreateWorkout.OnDisabledState.IconLeftImage = null;
            this.CreateWorkout.OnDisabledState.IconRightImage = null;
            this.CreateWorkout.onHoverState.BorderColor = System.Drawing.Color.DarkCyan;
            this.CreateWorkout.onHoverState.BorderRadius = 100;
            this.CreateWorkout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateWorkout.onHoverState.BorderThickness = 3;
            this.CreateWorkout.onHoverState.FillColor = System.Drawing.Color.CadetBlue;
            this.CreateWorkout.onHoverState.ForeColor = System.Drawing.Color.White;
            this.CreateWorkout.onHoverState.IconLeftImage = null;
            this.CreateWorkout.onHoverState.IconRightImage = null;
            this.CreateWorkout.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.CreateWorkout.OnIdleState.BorderRadius = 100;
            this.CreateWorkout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateWorkout.OnIdleState.BorderThickness = 3;
            this.CreateWorkout.OnIdleState.FillColor = System.Drawing.Color.LightCyan;
            this.CreateWorkout.OnIdleState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.CreateWorkout.OnIdleState.IconLeftImage = null;
            this.CreateWorkout.OnIdleState.IconRightImage = null;
            this.CreateWorkout.OnPressedState.BorderColor = System.Drawing.Color.DarkCyan;
            this.CreateWorkout.OnPressedState.BorderRadius = 100;
            this.CreateWorkout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateWorkout.OnPressedState.BorderThickness = 3;
            this.CreateWorkout.OnPressedState.FillColor = System.Drawing.Color.LightCyan;
            this.CreateWorkout.OnPressedState.ForeColor = System.Drawing.Color.DarkCyan;
            this.CreateWorkout.OnPressedState.IconLeftImage = null;
            this.CreateWorkout.OnPressedState.IconRightImage = null;
            this.CreateWorkout.Size = new System.Drawing.Size(249, 84);
            this.CreateWorkout.TabIndex = 3;
            this.CreateWorkout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.CreateWorkout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.CreateWorkout.TextMarginLeft = 0;
            this.CreateWorkout.TextPadding = new System.Windows.Forms.Padding(0);
            this.CreateWorkout.UseDefaultRadiusAndThickness = true;
            this.CreateWorkout.Click += new System.EventHandler(this.CreateWorkout_Click);
            // 
            // ChooseWorkout
            // 
            this.ChooseWorkout.AllowAnimations = true;
            this.ChooseWorkout.AllowMouseEffects = true;
            this.ChooseWorkout.AllowToggling = false;
            this.ChooseWorkout.AnimationSpeed = 200;
            this.ChooseWorkout.AutoGenerateColors = false;
            this.ChooseWorkout.AutoRoundBorders = false;
            this.ChooseWorkout.AutoSizeLeftIcon = true;
            this.ChooseWorkout.AutoSizeRightIcon = true;
            this.ChooseWorkout.BackColor = System.Drawing.Color.Transparent;
            this.ChooseWorkout.BackColor1 = System.Drawing.Color.LightCyan;
            this.ChooseWorkout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ChooseWorkout.BackgroundImage")));
            this.ChooseWorkout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ChooseWorkout.ButtonText = "Choose Workout";
            this.ChooseWorkout.ButtonTextMarginLeft = 0;
            this.ChooseWorkout.ColorContrastOnClick = 45;
            this.ChooseWorkout.ColorContrastOnHover = 45;
            this.ChooseWorkout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.ChooseWorkout.CustomizableEdges = borderEdges8;
            this.ChooseWorkout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ChooseWorkout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ChooseWorkout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ChooseWorkout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ChooseWorkout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ChooseWorkout.Font = new System.Drawing.Font("Segoe UI", 20F);
            this.ChooseWorkout.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.ChooseWorkout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ChooseWorkout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ChooseWorkout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ChooseWorkout.IconMarginLeft = 11;
            this.ChooseWorkout.IconPadding = 10;
            this.ChooseWorkout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ChooseWorkout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ChooseWorkout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ChooseWorkout.IconSize = 25;
            this.ChooseWorkout.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.ChooseWorkout.IdleBorderRadius = 100;
            this.ChooseWorkout.IdleBorderThickness = 3;
            this.ChooseWorkout.IdleFillColor = System.Drawing.Color.LightCyan;
            this.ChooseWorkout.IdleIconLeftImage = null;
            this.ChooseWorkout.IdleIconRightImage = null;
            this.ChooseWorkout.IndicateFocus = false;
            this.ChooseWorkout.Location = new System.Drawing.Point(481, 126);
            this.ChooseWorkout.Name = "ChooseWorkout";
            this.ChooseWorkout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ChooseWorkout.OnDisabledState.BorderRadius = 100;
            this.ChooseWorkout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ChooseWorkout.OnDisabledState.BorderThickness = 3;
            this.ChooseWorkout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ChooseWorkout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ChooseWorkout.OnDisabledState.IconLeftImage = null;
            this.ChooseWorkout.OnDisabledState.IconRightImage = null;
            this.ChooseWorkout.onHoverState.BorderColor = System.Drawing.Color.DarkCyan;
            this.ChooseWorkout.onHoverState.BorderRadius = 100;
            this.ChooseWorkout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ChooseWorkout.onHoverState.BorderThickness = 3;
            this.ChooseWorkout.onHoverState.FillColor = System.Drawing.Color.CadetBlue;
            this.ChooseWorkout.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ChooseWorkout.onHoverState.IconLeftImage = null;
            this.ChooseWorkout.onHoverState.IconRightImage = null;
            this.ChooseWorkout.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.ChooseWorkout.OnIdleState.BorderRadius = 100;
            this.ChooseWorkout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ChooseWorkout.OnIdleState.BorderThickness = 3;
            this.ChooseWorkout.OnIdleState.FillColor = System.Drawing.Color.LightCyan;
            this.ChooseWorkout.OnIdleState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.ChooseWorkout.OnIdleState.IconLeftImage = null;
            this.ChooseWorkout.OnIdleState.IconRightImage = null;
            this.ChooseWorkout.OnPressedState.BorderColor = System.Drawing.Color.DarkCyan;
            this.ChooseWorkout.OnPressedState.BorderRadius = 100;
            this.ChooseWorkout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ChooseWorkout.OnPressedState.BorderThickness = 3;
            this.ChooseWorkout.OnPressedState.FillColor = System.Drawing.Color.LightCyan;
            this.ChooseWorkout.OnPressedState.ForeColor = System.Drawing.Color.DarkCyan;
            this.ChooseWorkout.OnPressedState.IconLeftImage = null;
            this.ChooseWorkout.OnPressedState.IconRightImage = null;
            this.ChooseWorkout.Size = new System.Drawing.Size(249, 84);
            this.ChooseWorkout.TabIndex = 5;
            this.ChooseWorkout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ChooseWorkout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ChooseWorkout.TextMarginLeft = 0;
            this.ChooseWorkout.TextPadding = new System.Windows.Forms.Padding(0);
            this.ChooseWorkout.UseDefaultRadiusAndThickness = true;
            // 
            // DeitPlanning
            // 
            this.DeitPlanning.AllowAnimations = true;
            this.DeitPlanning.AllowMouseEffects = true;
            this.DeitPlanning.AllowToggling = false;
            this.DeitPlanning.AnimationSpeed = 200;
            this.DeitPlanning.AutoGenerateColors = false;
            this.DeitPlanning.AutoRoundBorders = false;
            this.DeitPlanning.AutoSizeLeftIcon = true;
            this.DeitPlanning.AutoSizeRightIcon = true;
            this.DeitPlanning.BackColor = System.Drawing.Color.Transparent;
            this.DeitPlanning.BackColor1 = System.Drawing.Color.LightCyan;
            this.DeitPlanning.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("DeitPlanning.BackgroundImage")));
            this.DeitPlanning.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DeitPlanning.ButtonText = "Diet Planning";
            this.DeitPlanning.ButtonTextMarginLeft = 0;
            this.DeitPlanning.ColorContrastOnClick = 45;
            this.DeitPlanning.ColorContrastOnHover = 45;
            this.DeitPlanning.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.DeitPlanning.CustomizableEdges = borderEdges9;
            this.DeitPlanning.DialogResult = System.Windows.Forms.DialogResult.None;
            this.DeitPlanning.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DeitPlanning.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DeitPlanning.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DeitPlanning.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.DeitPlanning.Font = new System.Drawing.Font("Segoe UI", 20F);
            this.DeitPlanning.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.DeitPlanning.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.DeitPlanning.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.DeitPlanning.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.DeitPlanning.IconMarginLeft = 11;
            this.DeitPlanning.IconPadding = 10;
            this.DeitPlanning.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.DeitPlanning.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.DeitPlanning.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.DeitPlanning.IconSize = 25;
            this.DeitPlanning.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.DeitPlanning.IdleBorderRadius = 100;
            this.DeitPlanning.IdleBorderThickness = 3;
            this.DeitPlanning.IdleFillColor = System.Drawing.Color.LightCyan;
            this.DeitPlanning.IdleIconLeftImage = null;
            this.DeitPlanning.IdleIconRightImage = null;
            this.DeitPlanning.IndicateFocus = false;
            this.DeitPlanning.Location = new System.Drawing.Point(67, 216);
            this.DeitPlanning.Name = "DeitPlanning";
            this.DeitPlanning.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DeitPlanning.OnDisabledState.BorderRadius = 100;
            this.DeitPlanning.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DeitPlanning.OnDisabledState.BorderThickness = 3;
            this.DeitPlanning.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DeitPlanning.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DeitPlanning.OnDisabledState.IconLeftImage = null;
            this.DeitPlanning.OnDisabledState.IconRightImage = null;
            this.DeitPlanning.onHoverState.BorderColor = System.Drawing.Color.DarkCyan;
            this.DeitPlanning.onHoverState.BorderRadius = 100;
            this.DeitPlanning.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DeitPlanning.onHoverState.BorderThickness = 3;
            this.DeitPlanning.onHoverState.FillColor = System.Drawing.Color.CadetBlue;
            this.DeitPlanning.onHoverState.ForeColor = System.Drawing.Color.White;
            this.DeitPlanning.onHoverState.IconLeftImage = null;
            this.DeitPlanning.onHoverState.IconRightImage = null;
            this.DeitPlanning.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.DeitPlanning.OnIdleState.BorderRadius = 100;
            this.DeitPlanning.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DeitPlanning.OnIdleState.BorderThickness = 3;
            this.DeitPlanning.OnIdleState.FillColor = System.Drawing.Color.LightCyan;
            this.DeitPlanning.OnIdleState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.DeitPlanning.OnIdleState.IconLeftImage = null;
            this.DeitPlanning.OnIdleState.IconRightImage = null;
            this.DeitPlanning.OnPressedState.BorderColor = System.Drawing.Color.DarkCyan;
            this.DeitPlanning.OnPressedState.BorderRadius = 100;
            this.DeitPlanning.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DeitPlanning.OnPressedState.BorderThickness = 3;
            this.DeitPlanning.OnPressedState.FillColor = System.Drawing.Color.LightCyan;
            this.DeitPlanning.OnPressedState.ForeColor = System.Drawing.Color.DarkCyan;
            this.DeitPlanning.OnPressedState.IconLeftImage = null;
            this.DeitPlanning.OnPressedState.IconRightImage = null;
            this.DeitPlanning.Size = new System.Drawing.Size(249, 84);
            this.DeitPlanning.TabIndex = 6;
            this.DeitPlanning.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.DeitPlanning.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.DeitPlanning.TextMarginLeft = 0;
            this.DeitPlanning.TextPadding = new System.Windows.Forms.Padding(0);
            this.DeitPlanning.UseDefaultRadiusAndThickness = true;
            // 
            // ChooseDiet
            // 
            this.ChooseDiet.AllowAnimations = true;
            this.ChooseDiet.AllowMouseEffects = true;
            this.ChooseDiet.AllowToggling = false;
            this.ChooseDiet.AnimationSpeed = 200;
            this.ChooseDiet.AutoGenerateColors = false;
            this.ChooseDiet.AutoRoundBorders = false;
            this.ChooseDiet.AutoSizeLeftIcon = true;
            this.ChooseDiet.AutoSizeRightIcon = true;
            this.ChooseDiet.BackColor = System.Drawing.Color.Transparent;
            this.ChooseDiet.BackColor1 = System.Drawing.Color.LightCyan;
            this.ChooseDiet.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ChooseDiet.BackgroundImage")));
            this.ChooseDiet.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ChooseDiet.ButtonText = "Choose Diet";
            this.ChooseDiet.ButtonTextMarginLeft = 0;
            this.ChooseDiet.ColorContrastOnClick = 45;
            this.ChooseDiet.ColorContrastOnHover = 45;
            this.ChooseDiet.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.ChooseDiet.CustomizableEdges = borderEdges10;
            this.ChooseDiet.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ChooseDiet.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ChooseDiet.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ChooseDiet.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ChooseDiet.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ChooseDiet.Font = new System.Drawing.Font("Segoe UI", 20F);
            this.ChooseDiet.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.ChooseDiet.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ChooseDiet.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ChooseDiet.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ChooseDiet.IconMarginLeft = 11;
            this.ChooseDiet.IconPadding = 10;
            this.ChooseDiet.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ChooseDiet.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ChooseDiet.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ChooseDiet.IconSize = 25;
            this.ChooseDiet.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.ChooseDiet.IdleBorderRadius = 100;
            this.ChooseDiet.IdleBorderThickness = 3;
            this.ChooseDiet.IdleFillColor = System.Drawing.Color.LightCyan;
            this.ChooseDiet.IdleIconLeftImage = null;
            this.ChooseDiet.IdleIconRightImage = null;
            this.ChooseDiet.IndicateFocus = false;
            this.ChooseDiet.Location = new System.Drawing.Point(481, 216);
            this.ChooseDiet.Name = "ChooseDiet";
            this.ChooseDiet.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ChooseDiet.OnDisabledState.BorderRadius = 100;
            this.ChooseDiet.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ChooseDiet.OnDisabledState.BorderThickness = 3;
            this.ChooseDiet.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ChooseDiet.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ChooseDiet.OnDisabledState.IconLeftImage = null;
            this.ChooseDiet.OnDisabledState.IconRightImage = null;
            this.ChooseDiet.onHoverState.BorderColor = System.Drawing.Color.DarkCyan;
            this.ChooseDiet.onHoverState.BorderRadius = 100;
            this.ChooseDiet.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ChooseDiet.onHoverState.BorderThickness = 3;
            this.ChooseDiet.onHoverState.FillColor = System.Drawing.Color.CadetBlue;
            this.ChooseDiet.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ChooseDiet.onHoverState.IconLeftImage = null;
            this.ChooseDiet.onHoverState.IconRightImage = null;
            this.ChooseDiet.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.ChooseDiet.OnIdleState.BorderRadius = 100;
            this.ChooseDiet.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ChooseDiet.OnIdleState.BorderThickness = 3;
            this.ChooseDiet.OnIdleState.FillColor = System.Drawing.Color.LightCyan;
            this.ChooseDiet.OnIdleState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.ChooseDiet.OnIdleState.IconLeftImage = null;
            this.ChooseDiet.OnIdleState.IconRightImage = null;
            this.ChooseDiet.OnPressedState.BorderColor = System.Drawing.Color.DarkCyan;
            this.ChooseDiet.OnPressedState.BorderRadius = 100;
            this.ChooseDiet.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ChooseDiet.OnPressedState.BorderThickness = 3;
            this.ChooseDiet.OnPressedState.FillColor = System.Drawing.Color.LightCyan;
            this.ChooseDiet.OnPressedState.ForeColor = System.Drawing.Color.DarkCyan;
            this.ChooseDiet.OnPressedState.IconLeftImage = null;
            this.ChooseDiet.OnPressedState.IconRightImage = null;
            this.ChooseDiet.Size = new System.Drawing.Size(249, 84);
            this.ChooseDiet.TabIndex = 7;
            this.ChooseDiet.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ChooseDiet.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ChooseDiet.TextMarginLeft = 0;
            this.ChooseDiet.TextPadding = new System.Windows.Forms.Padding(0);
            this.ChooseDiet.UseDefaultRadiusAndThickness = true;
            this.ChooseDiet.Click += new System.EventHandler(this.ChooseDiet_Click);
            // 
            // SessionBook
            // 
            this.SessionBook.AllowAnimations = true;
            this.SessionBook.AllowMouseEffects = true;
            this.SessionBook.AllowToggling = false;
            this.SessionBook.AnimationSpeed = 200;
            this.SessionBook.AutoGenerateColors = false;
            this.SessionBook.AutoRoundBorders = false;
            this.SessionBook.AutoSizeLeftIcon = true;
            this.SessionBook.AutoSizeRightIcon = true;
            this.SessionBook.BackColor = System.Drawing.Color.Transparent;
            this.SessionBook.BackColor1 = System.Drawing.Color.LightCyan;
            this.SessionBook.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SessionBook.BackgroundImage")));
            this.SessionBook.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SessionBook.ButtonText = "Book Session";
            this.SessionBook.ButtonTextMarginLeft = 0;
            this.SessionBook.ColorContrastOnClick = 45;
            this.SessionBook.ColorContrastOnHover = 45;
            this.SessionBook.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.SessionBook.CustomizableEdges = borderEdges11;
            this.SessionBook.DialogResult = System.Windows.Forms.DialogResult.None;
            this.SessionBook.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SessionBook.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SessionBook.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SessionBook.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.SessionBook.Font = new System.Drawing.Font("Segoe UI", 20F);
            this.SessionBook.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.SessionBook.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.SessionBook.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.SessionBook.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.SessionBook.IconMarginLeft = 11;
            this.SessionBook.IconPadding = 10;
            this.SessionBook.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.SessionBook.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.SessionBook.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.SessionBook.IconSize = 25;
            this.SessionBook.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.SessionBook.IdleBorderRadius = 100;
            this.SessionBook.IdleBorderThickness = 3;
            this.SessionBook.IdleFillColor = System.Drawing.Color.LightCyan;
            this.SessionBook.IdleIconLeftImage = null;
            this.SessionBook.IdleIconRightImage = null;
            this.SessionBook.IndicateFocus = false;
            this.SessionBook.Location = new System.Drawing.Point(67, 318);
            this.SessionBook.Name = "SessionBook";
            this.SessionBook.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SessionBook.OnDisabledState.BorderRadius = 100;
            this.SessionBook.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SessionBook.OnDisabledState.BorderThickness = 3;
            this.SessionBook.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SessionBook.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SessionBook.OnDisabledState.IconLeftImage = null;
            this.SessionBook.OnDisabledState.IconRightImage = null;
            this.SessionBook.onHoverState.BorderColor = System.Drawing.Color.DarkCyan;
            this.SessionBook.onHoverState.BorderRadius = 100;
            this.SessionBook.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SessionBook.onHoverState.BorderThickness = 3;
            this.SessionBook.onHoverState.FillColor = System.Drawing.Color.CadetBlue;
            this.SessionBook.onHoverState.ForeColor = System.Drawing.Color.White;
            this.SessionBook.onHoverState.IconLeftImage = null;
            this.SessionBook.onHoverState.IconRightImage = null;
            this.SessionBook.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.SessionBook.OnIdleState.BorderRadius = 100;
            this.SessionBook.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SessionBook.OnIdleState.BorderThickness = 3;
            this.SessionBook.OnIdleState.FillColor = System.Drawing.Color.LightCyan;
            this.SessionBook.OnIdleState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.SessionBook.OnIdleState.IconLeftImage = null;
            this.SessionBook.OnIdleState.IconRightImage = null;
            this.SessionBook.OnPressedState.BorderColor = System.Drawing.Color.DarkCyan;
            this.SessionBook.OnPressedState.BorderRadius = 100;
            this.SessionBook.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SessionBook.OnPressedState.BorderThickness = 3;
            this.SessionBook.OnPressedState.FillColor = System.Drawing.Color.LightCyan;
            this.SessionBook.OnPressedState.ForeColor = System.Drawing.Color.DarkCyan;
            this.SessionBook.OnPressedState.IconLeftImage = null;
            this.SessionBook.OnPressedState.IconRightImage = null;
            this.SessionBook.Size = new System.Drawing.Size(249, 84);
            this.SessionBook.TabIndex = 8;
            this.SessionBook.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.SessionBook.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.SessionBook.TextMarginLeft = 0;
            this.SessionBook.TextPadding = new System.Windows.Forms.Padding(0);
            this.SessionBook.UseDefaultRadiusAndThickness = true;
            // 
            // Rate
            // 
            this.Rate.AllowAnimations = true;
            this.Rate.AllowMouseEffects = true;
            this.Rate.AllowToggling = false;
            this.Rate.AnimationSpeed = 200;
            this.Rate.AutoGenerateColors = false;
            this.Rate.AutoRoundBorders = false;
            this.Rate.AutoSizeLeftIcon = true;
            this.Rate.AutoSizeRightIcon = true;
            this.Rate.BackColor = System.Drawing.Color.Transparent;
            this.Rate.BackColor1 = System.Drawing.Color.LightCyan;
            this.Rate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Rate.BackgroundImage")));
            this.Rate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Rate.ButtonText = "FeedBack";
            this.Rate.ButtonTextMarginLeft = 0;
            this.Rate.ColorContrastOnClick = 45;
            this.Rate.ColorContrastOnHover = 45;
            this.Rate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.Rate.CustomizableEdges = borderEdges12;
            this.Rate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Rate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Rate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Rate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Rate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Rate.Font = new System.Drawing.Font("Segoe UI", 20F);
            this.Rate.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.Rate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Rate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Rate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Rate.IconMarginLeft = 11;
            this.Rate.IconPadding = 10;
            this.Rate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Rate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Rate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Rate.IconSize = 25;
            this.Rate.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.Rate.IdleBorderRadius = 100;
            this.Rate.IdleBorderThickness = 3;
            this.Rate.IdleFillColor = System.Drawing.Color.LightCyan;
            this.Rate.IdleIconLeftImage = null;
            this.Rate.IdleIconRightImage = null;
            this.Rate.IndicateFocus = false;
            this.Rate.Location = new System.Drawing.Point(481, 318);
            this.Rate.Name = "Rate";
            this.Rate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Rate.OnDisabledState.BorderRadius = 100;
            this.Rate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Rate.OnDisabledState.BorderThickness = 3;
            this.Rate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Rate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Rate.OnDisabledState.IconLeftImage = null;
            this.Rate.OnDisabledState.IconRightImage = null;
            this.Rate.onHoverState.BorderColor = System.Drawing.Color.DarkCyan;
            this.Rate.onHoverState.BorderRadius = 100;
            this.Rate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Rate.onHoverState.BorderThickness = 3;
            this.Rate.onHoverState.FillColor = System.Drawing.Color.CadetBlue;
            this.Rate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Rate.onHoverState.IconLeftImage = null;
            this.Rate.onHoverState.IconRightImage = null;
            this.Rate.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.Rate.OnIdleState.BorderRadius = 100;
            this.Rate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Rate.OnIdleState.BorderThickness = 3;
            this.Rate.OnIdleState.FillColor = System.Drawing.Color.LightCyan;
            this.Rate.OnIdleState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.Rate.OnIdleState.IconLeftImage = null;
            this.Rate.OnIdleState.IconRightImage = null;
            this.Rate.OnPressedState.BorderColor = System.Drawing.Color.DarkCyan;
            this.Rate.OnPressedState.BorderRadius = 100;
            this.Rate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Rate.OnPressedState.BorderThickness = 3;
            this.Rate.OnPressedState.FillColor = System.Drawing.Color.LightCyan;
            this.Rate.OnPressedState.ForeColor = System.Drawing.Color.DarkCyan;
            this.Rate.OnPressedState.IconLeftImage = null;
            this.Rate.OnPressedState.IconRightImage = null;
            this.Rate.Size = new System.Drawing.Size(249, 84);
            this.Rate.TabIndex = 9;
            this.Rate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Rate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Rate.TextMarginLeft = 0;
            this.Rate.TextPadding = new System.Windows.Forms.Padding(0);
            this.Rate.UseDefaultRadiusAndThickness = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 40F);
            this.label1.Location = new System.Drawing.Point(97, 32);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(621, 76);
            this.label1.TabIndex = 10;
            this.label1.Text = "Member Homepage";
            // 
            // MemberMenu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.AppWorkspace;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.Rate);
            this.Controls.Add(this.SessionBook);
            this.Controls.Add(this.ChooseDiet);
            this.Controls.Add(this.DeitPlanning);
            this.Controls.Add(this.ChooseWorkout);
            this.Controls.Add(this.CreateWorkout);
            this.Name = "MemberMenu";
            this.Text = "MemberMenu";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton CreateWorkout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ChooseWorkout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton DeitPlanning;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ChooseDiet;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton SessionBook;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Rate;
        private System.Windows.Forms.Label label1;
    }
}