namespace DBPROJ_VF
{
    partial class TrainerMenu
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TrainerMenu));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.WorkoutReportsButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AppointmentsButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.DietReportsButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CreateWorkoutButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CreateDietPlanButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ViewFeedbackButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label1 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // WorkoutReportsButton
            // 
            this.WorkoutReportsButton.AllowAnimations = true;
            this.WorkoutReportsButton.AllowMouseEffects = true;
            this.WorkoutReportsButton.AllowToggling = false;
            this.WorkoutReportsButton.AnimationSpeed = 200;
            this.WorkoutReportsButton.AutoGenerateColors = false;
            this.WorkoutReportsButton.AutoRoundBorders = false;
            this.WorkoutReportsButton.AutoSizeLeftIcon = true;
            this.WorkoutReportsButton.AutoSizeRightIcon = true;
            this.WorkoutReportsButton.BackColor = System.Drawing.Color.Transparent;
            this.WorkoutReportsButton.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.WorkoutReportsButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("WorkoutReportsButton.BackgroundImage")));
            this.WorkoutReportsButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.WorkoutReportsButton.ButtonText = "Workout Reports";
            this.WorkoutReportsButton.ButtonTextMarginLeft = 0;
            this.WorkoutReportsButton.ColorContrastOnClick = 45;
            this.WorkoutReportsButton.ColorContrastOnHover = 45;
            this.WorkoutReportsButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges19.BottomLeft = true;
            borderEdges19.BottomRight = true;
            borderEdges19.TopLeft = true;
            borderEdges19.TopRight = true;
            this.WorkoutReportsButton.CustomizableEdges = borderEdges19;
            this.WorkoutReportsButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.WorkoutReportsButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.WorkoutReportsButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.WorkoutReportsButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.WorkoutReportsButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.WorkoutReportsButton.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.WorkoutReportsButton.ForeColor = System.Drawing.Color.White;
            this.WorkoutReportsButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.WorkoutReportsButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.WorkoutReportsButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.WorkoutReportsButton.IconMarginLeft = 11;
            this.WorkoutReportsButton.IconPadding = 10;
            this.WorkoutReportsButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.WorkoutReportsButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.WorkoutReportsButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.WorkoutReportsButton.IconSize = 25;
            this.WorkoutReportsButton.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.WorkoutReportsButton.IdleBorderRadius = 1;
            this.WorkoutReportsButton.IdleBorderThickness = 1;
            this.WorkoutReportsButton.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.WorkoutReportsButton.IdleIconLeftImage = null;
            this.WorkoutReportsButton.IdleIconRightImage = null;
            this.WorkoutReportsButton.IndicateFocus = false;
            this.WorkoutReportsButton.Location = new System.Drawing.Point(82, 354);
            this.WorkoutReportsButton.Name = "WorkoutReportsButton";
            this.WorkoutReportsButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.WorkoutReportsButton.OnDisabledState.BorderRadius = 1;
            this.WorkoutReportsButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.WorkoutReportsButton.OnDisabledState.BorderThickness = 1;
            this.WorkoutReportsButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.WorkoutReportsButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.WorkoutReportsButton.OnDisabledState.IconLeftImage = null;
            this.WorkoutReportsButton.OnDisabledState.IconRightImage = null;
            this.WorkoutReportsButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.WorkoutReportsButton.onHoverState.BorderRadius = 1;
            this.WorkoutReportsButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.WorkoutReportsButton.onHoverState.BorderThickness = 1;
            this.WorkoutReportsButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.WorkoutReportsButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.WorkoutReportsButton.onHoverState.IconLeftImage = null;
            this.WorkoutReportsButton.onHoverState.IconRightImage = null;
            this.WorkoutReportsButton.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.WorkoutReportsButton.OnIdleState.BorderRadius = 1;
            this.WorkoutReportsButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.WorkoutReportsButton.OnIdleState.BorderThickness = 1;
            this.WorkoutReportsButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.WorkoutReportsButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.WorkoutReportsButton.OnIdleState.IconLeftImage = null;
            this.WorkoutReportsButton.OnIdleState.IconRightImage = null;
            this.WorkoutReportsButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.WorkoutReportsButton.OnPressedState.BorderRadius = 1;
            this.WorkoutReportsButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.WorkoutReportsButton.OnPressedState.BorderThickness = 1;
            this.WorkoutReportsButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.WorkoutReportsButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.WorkoutReportsButton.OnPressedState.IconLeftImage = null;
            this.WorkoutReportsButton.OnPressedState.IconRightImage = null;
            this.WorkoutReportsButton.Size = new System.Drawing.Size(208, 62);
            this.WorkoutReportsButton.TabIndex = 5;
            this.WorkoutReportsButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.WorkoutReportsButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.WorkoutReportsButton.TextMarginLeft = 0;
            this.WorkoutReportsButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.WorkoutReportsButton.UseDefaultRadiusAndThickness = true;
            // 
            // AppointmentsButton
            // 
            this.AppointmentsButton.AllowAnimations = true;
            this.AppointmentsButton.AllowMouseEffects = true;
            this.AppointmentsButton.AllowToggling = false;
            this.AppointmentsButton.AnimationSpeed = 200;
            this.AppointmentsButton.AutoGenerateColors = false;
            this.AppointmentsButton.AutoRoundBorders = false;
            this.AppointmentsButton.AutoSizeLeftIcon = true;
            this.AppointmentsButton.AutoSizeRightIcon = true;
            this.AppointmentsButton.BackColor = System.Drawing.Color.Transparent;
            this.AppointmentsButton.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.AppointmentsButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AppointmentsButton.BackgroundImage")));
            this.AppointmentsButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AppointmentsButton.ButtonText = "Appointments";
            this.AppointmentsButton.ButtonTextMarginLeft = 0;
            this.AppointmentsButton.ColorContrastOnClick = 45;
            this.AppointmentsButton.ColorContrastOnHover = 45;
            this.AppointmentsButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges20.BottomLeft = true;
            borderEdges20.BottomRight = true;
            borderEdges20.TopLeft = true;
            borderEdges20.TopRight = true;
            this.AppointmentsButton.CustomizableEdges = borderEdges20;
            this.AppointmentsButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AppointmentsButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AppointmentsButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AppointmentsButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AppointmentsButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AppointmentsButton.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.AppointmentsButton.ForeColor = System.Drawing.Color.White;
            this.AppointmentsButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AppointmentsButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AppointmentsButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AppointmentsButton.IconMarginLeft = 11;
            this.AppointmentsButton.IconPadding = 10;
            this.AppointmentsButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AppointmentsButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AppointmentsButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AppointmentsButton.IconSize = 25;
            this.AppointmentsButton.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.AppointmentsButton.IdleBorderRadius = 1;
            this.AppointmentsButton.IdleBorderThickness = 1;
            this.AppointmentsButton.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.AppointmentsButton.IdleIconLeftImage = null;
            this.AppointmentsButton.IdleIconRightImage = null;
            this.AppointmentsButton.IndicateFocus = false;
            this.AppointmentsButton.Location = new System.Drawing.Point(674, 135);
            this.AppointmentsButton.Name = "AppointmentsButton";
            this.AppointmentsButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AppointmentsButton.OnDisabledState.BorderRadius = 1;
            this.AppointmentsButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AppointmentsButton.OnDisabledState.BorderThickness = 1;
            this.AppointmentsButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AppointmentsButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AppointmentsButton.OnDisabledState.IconLeftImage = null;
            this.AppointmentsButton.OnDisabledState.IconRightImage = null;
            this.AppointmentsButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AppointmentsButton.onHoverState.BorderRadius = 1;
            this.AppointmentsButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AppointmentsButton.onHoverState.BorderThickness = 1;
            this.AppointmentsButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AppointmentsButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AppointmentsButton.onHoverState.IconLeftImage = null;
            this.AppointmentsButton.onHoverState.IconRightImage = null;
            this.AppointmentsButton.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.AppointmentsButton.OnIdleState.BorderRadius = 1;
            this.AppointmentsButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AppointmentsButton.OnIdleState.BorderThickness = 1;
            this.AppointmentsButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.AppointmentsButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AppointmentsButton.OnIdleState.IconLeftImage = null;
            this.AppointmentsButton.OnIdleState.IconRightImage = null;
            this.AppointmentsButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AppointmentsButton.OnPressedState.BorderRadius = 1;
            this.AppointmentsButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AppointmentsButton.OnPressedState.BorderThickness = 1;
            this.AppointmentsButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AppointmentsButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AppointmentsButton.OnPressedState.IconLeftImage = null;
            this.AppointmentsButton.OnPressedState.IconRightImage = null;
            this.AppointmentsButton.Size = new System.Drawing.Size(208, 62);
            this.AppointmentsButton.TabIndex = 4;
            this.AppointmentsButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AppointmentsButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AppointmentsButton.TextMarginLeft = 0;
            this.AppointmentsButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.AppointmentsButton.UseDefaultRadiusAndThickness = true;
            // 
            // DietReportsButton
            // 
            this.DietReportsButton.AllowAnimations = true;
            this.DietReportsButton.AllowMouseEffects = true;
            this.DietReportsButton.AllowToggling = false;
            this.DietReportsButton.AnimationSpeed = 200;
            this.DietReportsButton.AutoGenerateColors = false;
            this.DietReportsButton.AutoRoundBorders = false;
            this.DietReportsButton.AutoSizeLeftIcon = true;
            this.DietReportsButton.AutoSizeRightIcon = true;
            this.DietReportsButton.BackColor = System.Drawing.Color.Transparent;
            this.DietReportsButton.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.DietReportsButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("DietReportsButton.BackgroundImage")));
            this.DietReportsButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DietReportsButton.ButtonText = "Diet Reports";
            this.DietReportsButton.ButtonTextMarginLeft = 0;
            this.DietReportsButton.ColorContrastOnClick = 45;
            this.DietReportsButton.ColorContrastOnHover = 45;
            this.DietReportsButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges21.BottomLeft = true;
            borderEdges21.BottomRight = true;
            borderEdges21.TopLeft = true;
            borderEdges21.TopRight = true;
            this.DietReportsButton.CustomizableEdges = borderEdges21;
            this.DietReportsButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.DietReportsButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DietReportsButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DietReportsButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DietReportsButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.DietReportsButton.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DietReportsButton.ForeColor = System.Drawing.Color.White;
            this.DietReportsButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.DietReportsButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.DietReportsButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.DietReportsButton.IconMarginLeft = 11;
            this.DietReportsButton.IconPadding = 10;
            this.DietReportsButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.DietReportsButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.DietReportsButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.DietReportsButton.IconSize = 25;
            this.DietReportsButton.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.DietReportsButton.IdleBorderRadius = 1;
            this.DietReportsButton.IdleBorderThickness = 1;
            this.DietReportsButton.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.DietReportsButton.IdleIconLeftImage = null;
            this.DietReportsButton.IdleIconRightImage = null;
            this.DietReportsButton.IndicateFocus = false;
            this.DietReportsButton.Location = new System.Drawing.Point(674, 241);
            this.DietReportsButton.Name = "DietReportsButton";
            this.DietReportsButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.DietReportsButton.OnDisabledState.BorderRadius = 1;
            this.DietReportsButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DietReportsButton.OnDisabledState.BorderThickness = 1;
            this.DietReportsButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DietReportsButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.DietReportsButton.OnDisabledState.IconLeftImage = null;
            this.DietReportsButton.OnDisabledState.IconRightImage = null;
            this.DietReportsButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.DietReportsButton.onHoverState.BorderRadius = 1;
            this.DietReportsButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DietReportsButton.onHoverState.BorderThickness = 1;
            this.DietReportsButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.DietReportsButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.DietReportsButton.onHoverState.IconLeftImage = null;
            this.DietReportsButton.onHoverState.IconRightImage = null;
            this.DietReportsButton.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.DietReportsButton.OnIdleState.BorderRadius = 1;
            this.DietReportsButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DietReportsButton.OnIdleState.BorderThickness = 1;
            this.DietReportsButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.DietReportsButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.DietReportsButton.OnIdleState.IconLeftImage = null;
            this.DietReportsButton.OnIdleState.IconRightImage = null;
            this.DietReportsButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.DietReportsButton.OnPressedState.BorderRadius = 1;
            this.DietReportsButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.DietReportsButton.OnPressedState.BorderThickness = 1;
            this.DietReportsButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.DietReportsButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.DietReportsButton.OnPressedState.IconLeftImage = null;
            this.DietReportsButton.OnPressedState.IconRightImage = null;
            this.DietReportsButton.Size = new System.Drawing.Size(208, 62);
            this.DietReportsButton.TabIndex = 6;
            this.DietReportsButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.DietReportsButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.DietReportsButton.TextMarginLeft = 0;
            this.DietReportsButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.DietReportsButton.UseDefaultRadiusAndThickness = true;
            // 
            // CreateWorkoutButton
            // 
            this.CreateWorkoutButton.AllowAnimations = true;
            this.CreateWorkoutButton.AllowMouseEffects = true;
            this.CreateWorkoutButton.AllowToggling = false;
            this.CreateWorkoutButton.AnimationSpeed = 200;
            this.CreateWorkoutButton.AutoGenerateColors = false;
            this.CreateWorkoutButton.AutoRoundBorders = false;
            this.CreateWorkoutButton.AutoSizeLeftIcon = true;
            this.CreateWorkoutButton.AutoSizeRightIcon = true;
            this.CreateWorkoutButton.BackColor = System.Drawing.Color.Transparent;
            this.CreateWorkoutButton.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.CreateWorkoutButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CreateWorkoutButton.BackgroundImage")));
            this.CreateWorkoutButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateWorkoutButton.ButtonText = "Create Workout Plan";
            this.CreateWorkoutButton.ButtonTextMarginLeft = 0;
            this.CreateWorkoutButton.ColorContrastOnClick = 45;
            this.CreateWorkoutButton.ColorContrastOnHover = 45;
            this.CreateWorkoutButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges22.BottomLeft = true;
            borderEdges22.BottomRight = true;
            borderEdges22.TopLeft = true;
            borderEdges22.TopRight = true;
            this.CreateWorkoutButton.CustomizableEdges = borderEdges22;
            this.CreateWorkoutButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.CreateWorkoutButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CreateWorkoutButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CreateWorkoutButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CreateWorkoutButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.CreateWorkoutButton.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.CreateWorkoutButton.ForeColor = System.Drawing.Color.White;
            this.CreateWorkoutButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.CreateWorkoutButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.CreateWorkoutButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.CreateWorkoutButton.IconMarginLeft = 11;
            this.CreateWorkoutButton.IconPadding = 10;
            this.CreateWorkoutButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.CreateWorkoutButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.CreateWorkoutButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.CreateWorkoutButton.IconSize = 25;
            this.CreateWorkoutButton.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.CreateWorkoutButton.IdleBorderRadius = 1;
            this.CreateWorkoutButton.IdleBorderThickness = 1;
            this.CreateWorkoutButton.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.CreateWorkoutButton.IdleIconLeftImage = null;
            this.CreateWorkoutButton.IdleIconRightImage = null;
            this.CreateWorkoutButton.IndicateFocus = false;
            this.CreateWorkoutButton.Location = new System.Drawing.Point(82, 135);
            this.CreateWorkoutButton.Name = "CreateWorkoutButton";
            this.CreateWorkoutButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CreateWorkoutButton.OnDisabledState.BorderRadius = 1;
            this.CreateWorkoutButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateWorkoutButton.OnDisabledState.BorderThickness = 1;
            this.CreateWorkoutButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CreateWorkoutButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CreateWorkoutButton.OnDisabledState.IconLeftImage = null;
            this.CreateWorkoutButton.OnDisabledState.IconRightImage = null;
            this.CreateWorkoutButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CreateWorkoutButton.onHoverState.BorderRadius = 1;
            this.CreateWorkoutButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateWorkoutButton.onHoverState.BorderThickness = 1;
            this.CreateWorkoutButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CreateWorkoutButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.CreateWorkoutButton.onHoverState.IconLeftImage = null;
            this.CreateWorkoutButton.onHoverState.IconRightImage = null;
            this.CreateWorkoutButton.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.CreateWorkoutButton.OnIdleState.BorderRadius = 1;
            this.CreateWorkoutButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateWorkoutButton.OnIdleState.BorderThickness = 1;
            this.CreateWorkoutButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.CreateWorkoutButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.CreateWorkoutButton.OnIdleState.IconLeftImage = null;
            this.CreateWorkoutButton.OnIdleState.IconRightImage = null;
            this.CreateWorkoutButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CreateWorkoutButton.OnPressedState.BorderRadius = 1;
            this.CreateWorkoutButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateWorkoutButton.OnPressedState.BorderThickness = 1;
            this.CreateWorkoutButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CreateWorkoutButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.CreateWorkoutButton.OnPressedState.IconLeftImage = null;
            this.CreateWorkoutButton.OnPressedState.IconRightImage = null;
            this.CreateWorkoutButton.Size = new System.Drawing.Size(208, 62);
            this.CreateWorkoutButton.TabIndex = 7;
            this.CreateWorkoutButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.CreateWorkoutButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.CreateWorkoutButton.TextMarginLeft = 0;
            this.CreateWorkoutButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.CreateWorkoutButton.UseDefaultRadiusAndThickness = true;
            // 
            // CreateDietPlanButton
            // 
            this.CreateDietPlanButton.AllowAnimations = true;
            this.CreateDietPlanButton.AllowMouseEffects = true;
            this.CreateDietPlanButton.AllowToggling = false;
            this.CreateDietPlanButton.AnimationSpeed = 200;
            this.CreateDietPlanButton.AutoGenerateColors = false;
            this.CreateDietPlanButton.AutoRoundBorders = false;
            this.CreateDietPlanButton.AutoSizeLeftIcon = true;
            this.CreateDietPlanButton.AutoSizeRightIcon = true;
            this.CreateDietPlanButton.BackColor = System.Drawing.Color.Transparent;
            this.CreateDietPlanButton.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.CreateDietPlanButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CreateDietPlanButton.BackgroundImage")));
            this.CreateDietPlanButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateDietPlanButton.ButtonText = "Create Diet Plan";
            this.CreateDietPlanButton.ButtonTextMarginLeft = 0;
            this.CreateDietPlanButton.ColorContrastOnClick = 45;
            this.CreateDietPlanButton.ColorContrastOnHover = 45;
            this.CreateDietPlanButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges23.BottomLeft = true;
            borderEdges23.BottomRight = true;
            borderEdges23.TopLeft = true;
            borderEdges23.TopRight = true;
            this.CreateDietPlanButton.CustomizableEdges = borderEdges23;
            this.CreateDietPlanButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.CreateDietPlanButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CreateDietPlanButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CreateDietPlanButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CreateDietPlanButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.CreateDietPlanButton.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.CreateDietPlanButton.ForeColor = System.Drawing.Color.White;
            this.CreateDietPlanButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.CreateDietPlanButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.CreateDietPlanButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.CreateDietPlanButton.IconMarginLeft = 11;
            this.CreateDietPlanButton.IconPadding = 10;
            this.CreateDietPlanButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.CreateDietPlanButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.CreateDietPlanButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.CreateDietPlanButton.IconSize = 25;
            this.CreateDietPlanButton.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.CreateDietPlanButton.IdleBorderRadius = 1;
            this.CreateDietPlanButton.IdleBorderThickness = 1;
            this.CreateDietPlanButton.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.CreateDietPlanButton.IdleIconLeftImage = null;
            this.CreateDietPlanButton.IdleIconRightImage = null;
            this.CreateDietPlanButton.IndicateFocus = false;
            this.CreateDietPlanButton.Location = new System.Drawing.Point(82, 250);
            this.CreateDietPlanButton.Name = "CreateDietPlanButton";
            this.CreateDietPlanButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CreateDietPlanButton.OnDisabledState.BorderRadius = 1;
            this.CreateDietPlanButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateDietPlanButton.OnDisabledState.BorderThickness = 1;
            this.CreateDietPlanButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CreateDietPlanButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CreateDietPlanButton.OnDisabledState.IconLeftImage = null;
            this.CreateDietPlanButton.OnDisabledState.IconRightImage = null;
            this.CreateDietPlanButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CreateDietPlanButton.onHoverState.BorderRadius = 1;
            this.CreateDietPlanButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateDietPlanButton.onHoverState.BorderThickness = 1;
            this.CreateDietPlanButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CreateDietPlanButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.CreateDietPlanButton.onHoverState.IconLeftImage = null;
            this.CreateDietPlanButton.onHoverState.IconRightImage = null;
            this.CreateDietPlanButton.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.CreateDietPlanButton.OnIdleState.BorderRadius = 1;
            this.CreateDietPlanButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateDietPlanButton.OnIdleState.BorderThickness = 1;
            this.CreateDietPlanButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.CreateDietPlanButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.CreateDietPlanButton.OnIdleState.IconLeftImage = null;
            this.CreateDietPlanButton.OnIdleState.IconRightImage = null;
            this.CreateDietPlanButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CreateDietPlanButton.OnPressedState.BorderRadius = 1;
            this.CreateDietPlanButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CreateDietPlanButton.OnPressedState.BorderThickness = 1;
            this.CreateDietPlanButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CreateDietPlanButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.CreateDietPlanButton.OnPressedState.IconLeftImage = null;
            this.CreateDietPlanButton.OnPressedState.IconRightImage = null;
            this.CreateDietPlanButton.Size = new System.Drawing.Size(208, 62);
            this.CreateDietPlanButton.TabIndex = 8;
            this.CreateDietPlanButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.CreateDietPlanButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.CreateDietPlanButton.TextMarginLeft = 0;
            this.CreateDietPlanButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.CreateDietPlanButton.UseDefaultRadiusAndThickness = true;
            this.CreateDietPlanButton.Click += new System.EventHandler(this.CreateDietPlanButton_Click);
            // 
            // ViewFeedbackButton
            // 
            this.ViewFeedbackButton.AllowAnimations = true;
            this.ViewFeedbackButton.AllowMouseEffects = true;
            this.ViewFeedbackButton.AllowToggling = false;
            this.ViewFeedbackButton.AnimationSpeed = 200;
            this.ViewFeedbackButton.AutoGenerateColors = false;
            this.ViewFeedbackButton.AutoRoundBorders = false;
            this.ViewFeedbackButton.AutoSizeLeftIcon = true;
            this.ViewFeedbackButton.AutoSizeRightIcon = true;
            this.ViewFeedbackButton.BackColor = System.Drawing.Color.Transparent;
            this.ViewFeedbackButton.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.ViewFeedbackButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ViewFeedbackButton.BackgroundImage")));
            this.ViewFeedbackButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ViewFeedbackButton.ButtonText = "View Feedback";
            this.ViewFeedbackButton.ButtonTextMarginLeft = 0;
            this.ViewFeedbackButton.ColorContrastOnClick = 45;
            this.ViewFeedbackButton.ColorContrastOnHover = 45;
            this.ViewFeedbackButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges24.BottomLeft = true;
            borderEdges24.BottomRight = true;
            borderEdges24.TopLeft = true;
            borderEdges24.TopRight = true;
            this.ViewFeedbackButton.CustomizableEdges = borderEdges24;
            this.ViewFeedbackButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ViewFeedbackButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ViewFeedbackButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ViewFeedbackButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ViewFeedbackButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ViewFeedbackButton.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ViewFeedbackButton.ForeColor = System.Drawing.Color.White;
            this.ViewFeedbackButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ViewFeedbackButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ViewFeedbackButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ViewFeedbackButton.IconMarginLeft = 11;
            this.ViewFeedbackButton.IconPadding = 10;
            this.ViewFeedbackButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ViewFeedbackButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ViewFeedbackButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ViewFeedbackButton.IconSize = 25;
            this.ViewFeedbackButton.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.ViewFeedbackButton.IdleBorderRadius = 1;
            this.ViewFeedbackButton.IdleBorderThickness = 1;
            this.ViewFeedbackButton.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.ViewFeedbackButton.IdleIconLeftImage = null;
            this.ViewFeedbackButton.IdleIconRightImage = null;
            this.ViewFeedbackButton.IndicateFocus = false;
            this.ViewFeedbackButton.Location = new System.Drawing.Point(674, 354);
            this.ViewFeedbackButton.Name = "ViewFeedbackButton";
            this.ViewFeedbackButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ViewFeedbackButton.OnDisabledState.BorderRadius = 1;
            this.ViewFeedbackButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ViewFeedbackButton.OnDisabledState.BorderThickness = 1;
            this.ViewFeedbackButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ViewFeedbackButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ViewFeedbackButton.OnDisabledState.IconLeftImage = null;
            this.ViewFeedbackButton.OnDisabledState.IconRightImage = null;
            this.ViewFeedbackButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ViewFeedbackButton.onHoverState.BorderRadius = 1;
            this.ViewFeedbackButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ViewFeedbackButton.onHoverState.BorderThickness = 1;
            this.ViewFeedbackButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ViewFeedbackButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ViewFeedbackButton.onHoverState.IconLeftImage = null;
            this.ViewFeedbackButton.onHoverState.IconRightImage = null;
            this.ViewFeedbackButton.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.ViewFeedbackButton.OnIdleState.BorderRadius = 1;
            this.ViewFeedbackButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ViewFeedbackButton.OnIdleState.BorderThickness = 1;
            this.ViewFeedbackButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.ViewFeedbackButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ViewFeedbackButton.OnIdleState.IconLeftImage = null;
            this.ViewFeedbackButton.OnIdleState.IconRightImage = null;
            this.ViewFeedbackButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ViewFeedbackButton.OnPressedState.BorderRadius = 1;
            this.ViewFeedbackButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ViewFeedbackButton.OnPressedState.BorderThickness = 1;
            this.ViewFeedbackButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ViewFeedbackButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ViewFeedbackButton.OnPressedState.IconLeftImage = null;
            this.ViewFeedbackButton.OnPressedState.IconRightImage = null;
            this.ViewFeedbackButton.Size = new System.Drawing.Size(208, 62);
            this.ViewFeedbackButton.TabIndex = 9;
            this.ViewFeedbackButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ViewFeedbackButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ViewFeedbackButton.TextMarginLeft = 0;
            this.ViewFeedbackButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.ViewFeedbackButton.UseDefaultRadiusAndThickness = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.label1.Location = new System.Drawing.Point(17, 17);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(351, 46);
            this.label1.TabIndex = 10;
            this.label1.Text = "Welcome Trainer!";
            // 
            // TrainerMenu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.ClientSize = new System.Drawing.Size(942, 482);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.ViewFeedbackButton);
            this.Controls.Add(this.CreateDietPlanButton);
            this.Controls.Add(this.CreateWorkoutButton);
            this.Controls.Add(this.DietReportsButton);
            this.Controls.Add(this.WorkoutReportsButton);
            this.Controls.Add(this.AppointmentsButton);
            this.Name = "TrainerMenu";
            this.RightToLeftLayout = true;
            this.Text = "TrainerMenu";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton WorkoutReportsButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AppointmentsButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton DietReportsButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton CreateWorkoutButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton CreateDietPlanButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ViewFeedbackButton;
        private System.Windows.Forms.Label label1;
    }
}