SELECT * FROM Gym_Member
CREATE TABLE Workout_Plan(
	id INT IDENTITY(1,1) PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	);
CREATE TABLE Diet_Plan(
	id INT IDENTITY(1,1) PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	purpose VARCHAR(50) NOT NULL,
	);
CREATE TABLE GYM_OWNER(
	UName VARCHAR(50) PRIMARY KEY NOT NULL,
	pWord VARCHAR(50) NOT NULL,
	fName VARCHAR(50) NOT NULL,
	lName VARCHAR(50) NOT NULL,
	DOB DATE
	);
CREATE TABLE Gym_Admin(
	UName VARCHAR(50) PRIMARY KEY NOT NULL,
	pWord VARCHAR(50) NOT NULL,
	fName VARCHAR(50) NOT NULL,
	lName VARCHAR(50) NOT NULL,
	DOB DATE
	);
CREATE TABLE Gym(
	id int IDENTITY(1,1) PRIMARY KEY,
	rating FLOAT(2) DEFAULT 0,
	location VARCHAR(50) NOT NULL,
	ownerUName VARCHAR(50),
	noMembers INT DEFAULT 0,
	noTrainers INT DEFAULT 0,
	finances INT DEFAULT 0,
	FOREIGN KEY (ownerUName) REFERENCES GYM_OWNER(UName) ON DELETE CASCADE
	);
CREATE TABLE Trainer(
	UName VARCHAR(50) PRIMARY KEY NOT NULL,
	pWord VARCHAR(50) NOT NULL,
	fName VARCHAR(50) NOT NULL,
	lName VARCHAR(50) NOT NULL, 
	gender VARCHAR(50),
	DOB DATE, 
	exp_lvl INT DEFAULT 0,
	rating FLOAT(2),
	gym_ID INT,
	startDate DATE,
	FOREIGN KEY (gym_ID) REFERENCES Gym(id) ON DELETE CASCADE
	);

CREATE TABLE Gym_Member(
	UName VARCHAR(50) PRIMARY KEY NOT NULL,
	pWord VARCHAR(50) NOT NULL,
	fName VARCHAR(50) NOT NULL,
	lName VARCHAR(50) NOT NULL, 
	DOB DATE, 
	wieght INT, 
	reg_date DATE NOT NULL, 
	goal VARCHAR(50), 
	gender VARCHAR(50), 
	subscription VARCHAR(50) NOT NULL, 
	trnUName VARCHAR(50),
	height INT,
	gym_ID INT,
	workPlan INT DEFAULT NULL,
	dietPlan INT DEFAULT NULL,
	FOREIGN KEY (workPlan) REFERENCES Workout_Plan(id),
	FOREIGN KEY (dietPlan) REFERENCES Diet_Plan(id),
	FOREIGN KEY (gym_ID) REFERENCES Gym(id) ON DELETE CASCADE,
	FOREIGN KEY (trnUname) REFERENCES Trainer(UName) 
	);

CREATE TABLE Alergy(
	UName VARCHAR(50),
	alergy VARCHAR(50),
	FOREIGN KEY (UName) REFERENCES Gym_Member(UName) ON DELETE CASCADE,
	PRIMARY KEY (UName, alergy)
	);
CREATE TABLE TRN_PAST_GYM(
	UName VARCHAR(50),
	gymName VARCHAR(50),
	FOREIGN KEY (UName) REFERENCES Trainer(UName) ON DELETE CASCADE,
	PRIMARY KEY (UName, gymName)
	);

CREATE TABLE Training_Session(
	sessionID INT IDENTITY(1,1) PRIMARY KEY,
	start_time TIME NOT NULL,
	end_time TIME NOT NULL,
	TrainerUName VARCHAR(50) ,
	MemberUName VARCHAR(50),
	FOREIGN KEY (TrainerUName) REFERENCES Trainer(UName) ON DELETE NO ACTION,
	FOREIGN KEY (MemberUName) REFERENCES Gym_Member(UName) ON DELETE CASCADE
	);
CREATE TABLE Franchise_Application(
	id INT IDENTITY(1,1) PRIMARY KEY,
	location VARCHAR(50) NOT NULL,
	demand INT NOT NULL,
	proposition VARCHAR(50) NOT NULL,
	ownerUName VARCHAR(50),
	FOREIGN KEY (ownerUName) REFERENCES GYM_OWNER(UName) ON DELETE CASCADE
	);

CREATE TABLE Trainer_Feedback(
	id INT IDENTITY(1,1) PRIMARY KEY,
	rating FLOAT(2) NOT NULL,
	comment VARCHAR(50) NOT NULL,
	trainerUName VARCHAR(50) ,
	memberUName VARCHAR(50),
	FOREIGN KEY (trainerUName) REFERENCES Trainer(UName),
	FOREIGN KEY (memberUName) REFERENCES Gym_Member(UName) ON DELETE CASCADE
	);

CREATE TABLE exercise(
	name VARCHAR(50) PRIMARY KEY NOT NULL,
	machine VARCHAR(50) NOT NULL,
	Setss INT,
	Reps INT,
	RestInterval INT
	);
CREATE TABLE ExerciseInDay(
	exerciseName VARCHAR(50) ,
	dayFK VARCHAR(50),
	planFK INT,
	FOREIGN KEY (exerciseName) REFERENCES exercise(name) ON DELETE CASCADE,
	FOREIGN KEY (planFK) REFERENCES Workout_Plan(id) ON DELETE CASCADE,
	PRIMARY KEY (dayFK, planFK)
	);
CREATE TABLE Meal(
	name VARCHAR(50) PRIMARY KEY NOT NULL,
	portionSize INT NOT NULL,
	protein INT NOT NULL,
	carbs INT NOT NULL,
	fat INT NOT NULL,
	fiber INT NOT NULL,
	Allergen VARCHAR(50)
	);
CREATE TABLE MealInDay(
	mealName VARCHAR(50),
	dayFK VARCHAR(50),
	planFK INT,
	FOREIGN KEY (mealName) REFERENCES Meal(name) ON DELETE CASCADE,
	FOREIGN KEY (planFK) REFERENCES Diet_Plan(id) ON DELETE CASCADE,
	PRIMARY KEY (dayFK, planFK)
	);

CREATE TABLE GYM_Attendance(
	id INT IDENTITY(1,1) PRIMARY KEY,
	memberUName VARCHAR(50),
	trainerUName VARCHAR(50),
	attendance FLOAT(2) NOT NULL,
	FOREIGN KEY (memberUName) REFERENCES Gym_Member(UName) ON DELETE CASCADE,
	FOREIGN KEY (trainerUName) REFERENCES Trainer(UName)
	);


