CREATE TABLE Gym_Member(
	UName VARCHAR(50) PRIMARY KEY NOT NULL,
	pWord VARCHAR(50) NOT NULL,
	fName VARCHAR(50) NOT NULL,
	lName VARCHAR(50) NOT NULL, 
	DOB DATE, 
	wieght INT, 
	reg_date DATE NOT NULL, 
	goal VARCHAR(50), 
	gender VARCHAR(50), 
	subscription VARCHAR(50) NOT NULL, 
	trnUName VARCHAR(50),
	height INT,
	FOREIGN KEY (trnUname) REFERENCES Trainer(UName) ON DELETE CASCADE
	);

CREATE TABLE Alergy(
	UName VARCHAR(50) PRIMARY KEY,
	alergy VARCHAR(50),
	FOREIGN KEY (UName) REFERENCES Gym_Member(UName) ON DELETE CASCADE,
	PRIMARY KEY (UName, alergy)
	);

CREATE TABLE Trainer(
	UName VARCHAR(50) PRIMARY KEY NOT NULL,
	pWord VARCHAR(50) NOT NULL,
	fName VARCHAR(50) NOT NULL,
	lName VARCHAR(50) NOT NULL, 
	gender VARCHAR(50),
	DOB DATE, 
	exp_lvl INT DEFAULT 0,
	rating FLOAT(2),
	startDate DATE
	);

CREATE TABLE TRN_PAST_GYM(
	UName VARCHAR(50),
	gymName VARCHAR(50),
	FOREIGN KEY (UName) REFERENCES Trainer(UName) ON DELETE CASCADE
	PRIMARY KEY (UName, gymName)
	);

CREATE TABLE Training_Session(
	sessionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	start_time TIME NOT NULL,
	end_time TIME NOT NULL,
	TrainerUName VARCHAR(50) ,
	MemberUName VARCHAR(50),
	FOREIGN KEY (TrainerUName) REFERENCES Trainer(UName) ON DELETE NO ACTION,
	FOREIGN KEY (MemberUName) REFERENCES Gym_Member(UName) ON DELETE CASCADE
	);
CREATE TABLE GYM_OWNER(
	UName VARCHAR(50) PRIMARY KEY NOT NULL,
	pWord VARCHAR(50) NOT NULL,
	fName VARCHAR(50) NOT NULL,
	lName VARCHAR(50) NOT NULL,
	DOB DATE
	);
CREATE TABLE Gym_Admin(
	UName VARCHAR(50) PRIMARY KEY NOT NULL,
	pWord VARCHAR(50) NOT NULL,
	fName VARCHAR(50) NOT NULL,
	lName VARCHAR(50) NOT NULL,
	DOB DATE
	);
CREATE TABLE Franchise_Application(
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	location VARCHAR(50) NOT NULL,
	demand INT NOT NULL,
	proposition VARCHAR(50) NOT NULL,
	adminUName VARCHAR(50) ,
	ownerUName VARCHAR(50),
	FOREIGN KEY (adminUName) REFERENCES Gym_Admin(UName) ON DELETE CASCADE,
	FOREIGN KEY (ownerUName) REFERENCES GYM_OWNER(UName) ON DELETE CASCADE
	);

CREATE TABLE Gym(
	id int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	rating FLOAT(2) DEFAULT 0,
	location VARCHAR(50) NOT NULL,
	ownerUName VARCHAR(50),
	noMembers INT DEFAULT 0,
	noTrainers INT DEFAULT 0,
	finances INT DEFAULT 0,
	FOREIGN KEY (ownerUName) REFERENCES GYM_OWNER(UName) ON DELETE CASCADE
	);
CREATE TABLE Trainer_Feedback(
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	rating FLOAT(2) NOT NULL,
	comment VARCHAR(50) NOT NULL,
	trainerUName VARCHAR(50) ,
	memberUName VARCHAR(50),
	FOREIGN KEY (trainerUName) REFERENCES Trainer(UName),
	FOREIGN KEY (memberUName) REFERENCES Gym_Member(UName) ON DELETE CASCADE
	);
CREATE TABLE Workout_Plan(
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	name VARCHAR(50) NOT NULL,
	type VARCHAR(50) NOT NULL,
	trainerUName VARCHAR(50) ,
	memUName VARCHAR(50),
	FOREIGN KEY (trainerUName) REFERENCES Trainer(UName),
	FOREIGN KEY (memUName) REFERENCES Gym_Member(UName) ON DELETE CASCADE
	);
CREATE TABLE workout_day(
	planID INT,
	wDay VARCHAR(50) NOT NULL,
	FOREIGN KEY (planID) REFERENCES Workout_Plan(id) ON DELETE CASCADE,
	PRIMARY KEY (planID, wDay)
	);

CREATE TABLE exercise(
	name VARCHAR(50) PRIMARY KEY NOT NULL,
	machine VARCHAR(50) NOT NULL,
	targetMuscle VARCHAR(50) NOT NULL
	);

CREATE TABLE ExerciseInDay(
	exerciseName VARCHAR(50) ,
	dayFK VARCHAR(50),
	planFK INT,
	FOREIGN KEY (exerciseName) REFERENCES exercise(name) ON DELETE CASCADE,
	FOREIGN KEY (planFK , dayFK) REFERENCES workout_day(planID,wDay) ON DELETE CASCADE,
	PRIMARY KEY (exerciseName, dayFK, planFK)
	);
CREATE TABLE Meal(
	name VARCHAR(50) PRIMARY KEY NOT NULL,
	portionSize INT NOT NULL,
	protein INT NOT NULL,
	carbs INT NOT NULL,
	fat INT NOT NULL,
	fiber INT NOT NULL
	);
CREATE TABLE Diet_Plan(
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	name VARCHAR(50) NOT NULL,
	type VARCHAR(50) NOT NULL,
	purpose VARCHAR(50) NOT NULL,
	trainerUName VARCHAR(50),
	memUName VARCHAR(50) ,
	FOREIGN KEY (trainerUName) REFERENCES Trainer(UName),
	FOREIGN KEY (memUName) REFERENCES Gym_Member(UName) ON DELETE CASCADE
	);
CREATE TABLE meal_day(
	planID INT,
	mDay VARCHAR(50) NOT NULL,
	FOREIGN KEY (planID) REFERENCES Diet_Plan(id) ON DELETE CASCADE,
	PRIMARY KEY (planID, mDay)
	);
CREATE TABLE MealInDay(
	mealName VARCHAR(50),
	dayFK VARCHAR(50),
	planFK INT,
	FOREIGN KEY (mealName) REFERENCES Meal(name) ON DELETE CASCADE,
	FOREIGN KEY (planFK,dayFK) REFERENCES meal_day(planID,mDay) ON DELETE CASCADE,
	PRIMARY KEY (mealName, dayFK, planFK)
	);
CREATE TABLE GYM_Attendance(
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	memberUName VARCHAR(50),
	trainerUName VARCHAR(50),
	attendance FLOAT(2) NOT NULL,
	FOREIGN KEY (memberUName) REFERENCES Gym_Member(UName) ON DELETE CASCADE,
	FOREIGN KEY (trainerUName) REFERENCES Trainer(UName)
	);
